parameters:
    vitre_php_console.connection.class: Vitre\PhpConsoleBundle\Connection

services:
    vitre_php_console.connection:
        class: %vitre_php_console.connection.class%
        arguments: [@service_container]
