parameters:
    vitre_php_console.console.class: Vitre\PhpConsoleBundle\Console

services:
    vitre_php_console:
        class: "%vitre_php_console.console.class%"
        arguments: ['@service_container']
